name: theta_rendering
description: A new Flutter package project.
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 

  # Theta packages
  theta_models:
    git:
      url: https://github.com/teta-so/theta_models.git
      ref: main

  light_logger:
  graphview:
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

dependency_overrides:
