name: theta
description: Build remote UIs.

version: 0.1.0-dev.1

repository: https://github.com/buildwiththeta/buildwiththeta
homepage: https://buildwiththeta.com
issue_tracker: https://github.com/buildwiththeta/buildwiththeta/issues
documentation: https://docs.page/buildwiththeta/buildwiththeta

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

scripts:
  gen: "flutter pub run build_runner build --delete-conflicting-outputs"

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  theta_analytics:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/analytics
      ref: main

  theta_models:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/models
      ref: main

  theta_rendering:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/rendering
      ref: main

  theta_open_widgets:
    git:
      url: https://github.com/buildwiththeta/buildwiththeta.git
      path: packages/widgets
      ref: main

  light_logger: ^0.0.3

  device_frame: ^1.0.0
  equatable: ^2.0.3
  either_dart: ^0.4.0
  http: ^0.13.5
  get_it: ^7.6.0
  provider: ^6.0.5
  collection: ^1.17.1
  hive: ^2.2.3
  meta: ^1.9.1

  reflectable: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  
  build_runner:
  source_gen:

flutter:
